[package]
name = "yamplate"
version = "0.1.0"
authors = ["Alexander Koval <kovalidis@gmail.com>"]
edition = "2018"

[lib]
name = "yamplate"
path = "src/lib.rs"

[[bin]]
name = "yamplate-bin"
path = "src/bin/main.rs"

[dependencies]
quire = { git = 'https://github.com/anti-social/rust-quire', rev="38fdc1f" }
combine = "3.6.6"
failure = "0.1.5"
failure_derive = "0.1.5"
argparse = "0.2.2"
